"""add new field: isbn13 in Book table

Revision ID: 1f175b136e2e
Revises: bea610459a7f
Create Date: 2025-02-18 14:22:48.791269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1f175b136e2e'
down_revision: Union[str, None] = 'bea610459a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn13', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.drop_constraint('book_isbn_key', type_='unique')
        batch_op.create_unique_constraint(None, ['isbn13'])
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('book_isbn_key', ['isbn'])
        batch_op.drop_column('isbn13')

    # ### end Alembic commands ###
