"""add "qrcode_img_link" column to BookTransaction table and constraint

Revision ID: 2f93406e3702
Revises: d4752d224f91
Create Date: 2025-03-06 16:27:13.225167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2f93406e3702'
down_revision: Union[str, None] = 'd4752d224f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booktransaction', schema=None) as batch_op:
        batch_op.alter_column('qr_code_image_link',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booktransaction', schema=None) as batch_op:
        batch_op.alter_column('qr_code_image_link',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
