"""add new field: pages and cover_image_link in Book table

Revision ID: 5f101ee486b1
Revises: 1f175b136e2e
Create Date: 2025-02-18 18:05:52.130593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5f101ee486b1'
down_revision: Union[str, None] = '1f175b136e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('pages', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['cover_image_link'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pages')
        batch_op.drop_column('cover_image_link')

    # ### end Alembic commands ###
