"""add "qrcode_img_link" column to BookTransaction table

Revision ID: d4752d224f91
Revises: a6902c13ef60
Create Date: 2025-03-06 16:24:17.909248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd4752d224f91'
down_revision: Union[str, None] = 'a6902c13ef60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booktransaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_image_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booktransaction', schema=None) as batch_op:
        batch_op.drop_column('qr_code_image_link')

    # ### end Alembic commands ###
